=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/sql/sqlTemplate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT templateConfig (table)*>

<!ELEMENT table ( select| selectPaging | selectCount | insert | update | delete | selectInsert | merge| createSelect)+>

<!-- dml sql example start -->
<!ELEMENT select (#PCDATA) >
<!ELEMENT selectCount (#PCDATA) >
<!ELEMENT selectPaging (#PCDATA) >
<!ELEMENT insert (#PCDATA) >
<!ELEMENT update (#PCDATA) >
<!ELEMENT delete (#PCDATA) >
<!ELEMENT selectInsert (#PCDATA) >
<!ELEMENT merge (#PCDATA) >
<!ELEMENT createSelect (#PCDATA)>
<!-- // dml sql example end -->

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/sql/tibero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE templateConfig SYSTEM  "sqlTemplate.dtd">

<templateConfig>
	<table>
		<select>
		<![CDATA[
select * from {{objectName}}
		]]>
		</select>
		
		<selectCount>
		<![CDATA[
SELECT COUNT(*) as "cnt" FROM ({{{selectQuery}}})
		]]>
		</selectCount>
		
		<selectPaging>
		<![CDATA[
SELECT * FROM ( 
	SELECT a.*, ROWNUM rnum 
	FROM ( 
		{{{selectQuery}}} 
		{{~#isNotEmpty sortColumn}}
		ORDER BY {{sortColumn}} 
		{{/isNotEmpty}} 
	) a WHERE ROWNUM <= #{endRow} 
) WHERE rnum > #{startRow}
		]]>
		</selectPaging>

        <!-- insert query -->
        <insert>
        <![CDATA[
insert into {{objectName}} ( 
{{#columnList}}
    {{addChar @index "" ","}}{{name}}
{{/columnList}}
)values(
	{{#columnList}}
	    {{addChar @index "" ","}} ?
	{{/columnList}}
)
		]]>
        </insert>
            
        <update>
        <![CDATA[
update {{objectName}} 
 set 
{{#columnList}}
    {{addChar @index "" ","}}{{name}} = ?
{{/columnList}}
		]]>
        </update>    
		
        <delete>
        <![CDATA[
delete from {{objectName}}
		]]>
        </delete>    
		
        <createSelect>
        <![CDATA[
CREATE TABLE {{objectName}}_backup AS
SELECT
	*
FROM {{objectName}}
WHERE condition;
		]]>
        </createSelect>    
		
        <merge>
        <![CDATA[
MERGE INTO {{objectName}} a
USING dual on (
	
)
when matched then 
	update 
	set 
		{{#columnList}}
		    {{addChar @index "" ","}}{{name}} = ?
		{{/columnList}}
when not matched then
	insert(
		{{#columnList}}
		    {{addChar @index "" ","}}{{name}}
		{{/columnList}}
	)values(
		{{#columnList}}
		    {{addChar @index "" ","}} ?
		{{/columnList}}
	)
		]]>
        </merge>
            
		
	</table>
</templateConfig>
