=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddlTemplate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT var-ddl (tableScript,viewScript,functionScript,procedureScript,triggerScript,indexScript,sequenceScript,alterAddColumn,alterRenameColumn,alterModifyColumn,alterDropColumn,renameTable)>
<!ELEMENT tableScript (#PCDATA)>
<!ELEMENT viewScript (#PCDATA)>
<!ELEMENT functionScript (#PCDATA)>
<!ELEMENT procedureScript (#PCDATA)>
<!ELEMENT triggerScript (#PCDATA)>
<!ELEMENT indexScript (#PCDATA)>
<!ELEMENT sequenceScript (#PCDATA)>
<!ELEMENT alterAddColumn (#PCDATA)>
<!ELEMENT alterRenameColumn (#PCDATA)>
<!ELEMENT alterModifyColumn (#PCDATA)>
<!ELEMENT alterDropColumn (#PCDATA)>
<!ELEMENT renameTable (#PCDATA) >

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddl_oracle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE var-ddl SYSTEM  "ddlTemplate.dtd">

<var-ddl>
	<!-- 테이블 생성-->
	<tableScript><![CDATA[

	]]></tableScript>

	<!-- view 생성-->
	<viewScript><![CDATA[

	]]></viewScript>

	<!-- function 생성-->
	<functionScript><![CDATA[

	]]></functionScript>

	<!-- procedure 생성-->
	<procedureScript><![CDATA[

	]]></procedureScript>

	<!-- trigger 생성-->
	<triggerScript><![CDATA[
		/* DROP TRIGGER ; */
		CREATE OR REPLACE
	]]></triggerScript>

	<!-- index 생성-->
	<indexScript><![CDATA[

	]]></indexScript>

	<!-- sequence 생성-->
	<sequenceScript><![CDATA[
{{#equals true ddlOption.addDropClause}}/* DROP SEQUENCE {{OBJECT_NAME}}; */
{{/equals}}
CREATE SEQUENCE "{{schema}}"."{{OBJECT_NAME}}"
MINVALUE {{MIN_VALUE}}
MAXVALUE {{MAX_VALUE}}
INCREMENT BY {{INCREMENT_BY}} START WITH {{LAST_NUMBER}}
CACHE {{CACHE_SIZE}} {{#equals 'Y' ORDER_FLAG}}ORDER{{else}}NOORDER{{/equals}} {{#equals 'Y' CYCLE_FLAG}}CYCLE{{else}}NOCYCLE{{/equals}};
	]]></sequenceScript>

	<!-- 컬럼 추가-->
	<alterAddColumn><![CDATA[
		alter table {{TABLE_NAME}} add ({{COLUMN_NAME}} {{DATA_TYPE}} {{DEFAULT_VALUE}})
	]]></alterAddColumn>

	<!-- 컬럼명 수정 추가-->
	<alterRenameColumn><![CDATA[
		alter table {{TABLE_NAME}} rename column {{COLUMN_NAME}} to {{NEW_COLUMN_NAME}}
	]]></alterRenameColumn>

	<!-- 컬럼 수정 추가-->
	<alterModifyColumn><![CDATA[
		alter table {{TABLE_NAME}} MODIFY({{COLUMN_NAME}} {{DATA_TYPE}} {{#equals true ddlOption.isNotNull}} not null {{/equals}} {{DEFAULT_VALUE}});
	]]></alterModifyColumn>

	<!-- 컬럼명 수정 추가-->
	<alterDropColumn><![CDATA[
		alter table {{TABLE_NAME}} DROP COLUMN {{COLUMN_NAME}}
	]]></alterDropColumn>

	<!-- 테이블명 수정 추가-->
	<renameTable><![CDATA[
		alter table {{TABLE_NAME}} rename to {{NEW_TABLE_NAME}};
	]]></renameTable>
</var-ddl>

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddl_mssql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE var-ddl SYSTEM  "ddlTemplate.dtd">

<var-ddl>
	<!-- 테이블 생성-->
	<tableScript><![CDATA[

	]]></tableScript>

	<!-- view 생성-->
	<viewScript><![CDATA[

	]]></viewScript>

	<!-- function 생성-->
	<functionScript><![CDATA[

	]]></functionScript>

	<!-- procedure 생성-->
	<procedureScript><![CDATA[

	]]></procedureScript>

	<!-- trigger 생성-->
	<triggerScript><![CDATA[
		/* DROP TRIGGER ; */
		CREATE OR REPLACE
	]]></triggerScript>

	<!-- index 생성-->
	<indexScript><![CDATA[

	]]></indexScript>

	<!-- sequence 생성-->
	<sequenceScript><![CDATA[
{{#equals true ddlOption.addDropClause}}/* DROP SEQUENCE {{OBJECT_NAME}}; */
{{/equals}}

CREATE SEQUENCE [{{schema}}].[{{OBJECT_NAME}}]
AS [int]
START WITH 0
INCREMENT BY {{INCREMENT_BY}}
MINVALUE {{MIN_VALUE}}
MAXVALUE {{MAX_VALUE}}
CACHE
	]]></sequenceScript>

	<!-- 컬럼 추가-->
	<alterAddColumn><![CDATA[
		alter table {{TABLE_NAME}} add {{COLUMN_NAME}} {{DATA_TYPE}} {{DEFAULT_VALUE}}
	]]></alterAddColumn>

	<!-- 컬럼명 수정 추가-->
	<alterRenameColumn><![CDATA[
		sp_rename '{{TABLE_NAME}}.[{{COLUMN_NAME}}]', '{{NEW_COLUMN_NAME}}'
	]]></alterRenameColumn>

	<!-- 컬럼 수정 추가-->
	<alterModifyColumn><![CDATA[
		alter table {{TABLE_NAME}} ALTER COLUMN {{COLUMN_NAME}} {{DATA_TYPE}} {{#equals true ddlOption.isNotNull}} not null {{/equals}} {{DEFAULT_VALUE}}
	]]></alterModifyColumn>

	<!-- 컬럼명 수정 추가-->
	<alterDropColumn><![CDATA[
		alter table {{TABLE_NAME}} DROP COLUMN {{COLUMN_NAME}}
	]]></alterDropColumn>

	<!-- 테이블명 수정 추가-->
	<renameTable><![CDATA[
		sp_rename '{{TABLE_NAME}}', '{{NEW_TABLE_NAME}}'
	]]></renameTable>
</var-ddl>

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddl_cubrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE var-ddl SYSTEM  "ddlTemplate.dtd">

<var-ddl>
	<!-- 테이블 생성-->
	<tableScript><![CDATA[

	]]></tableScript>

	<!-- view 생성-->
	<viewScript><![CDATA[

	]]></viewScript>

	<!-- function 생성-->
	<functionScript><![CDATA[
		CREATE FUNCTION {{OBJECT_NAME}} ({{ARGUMENTS}}) RETURN {{RETURN_TYPE}}
		AS LANGUAGE {{LANG}}
		NAME {{SOURCE}};
	]]></functionScript>

	<!-- procedure 생성-->
	<procedureScript><![CDATA[
		CREATE PROCEDURE {{OBJECT_NAME}} ({{ARGUMENTS}}) RETURN {{RETURN_TYPE}}
		AS LANGUAGE {{LANG}}
		NAME {{SOURCE}};
	]]></procedureScript>

	<!-- trigger 생성-->
	<triggerScript><![CDATA[
		/* DROP TRIGGER ; */
		CREATE OR REPLACE
	]]></triggerScript>

	<!-- index 생성-->
	<indexScript><![CDATA[

	]]></indexScript>

	<!-- sequence 생성-->
	<sequenceScript><![CDATA[
{{#equals true ddlOption.addDropClause}}/* DROP SERIAL {{OBJECT_NAME}}; */
{{/equals}}

CREATE SERIAL {{OBJECT_NAME}}
START WITH 1
INCREMENT BY {{INCREMENT_BY}}
MINVALUE {{MIN_VALUE}}
MAXVALUE {{MAX_VALUE}}
	]]></sequenceScript>

	<!-- 컬럼 추가-->
	<alterAddColumn><![CDATA[
		alter table {{TABLE_NAME}} add column {{COLUMN_NAME}} {{DATA_TYPE}} {{DEFAULT_VALUE}}
	]]></alterAddColumn>

	<!-- 컬럼명 수정 추가-->
	<alterRenameColumn><![CDATA[
		alter table {{TABLE_NAME}} rename column {{COLUMN_NAME}} as {{NEW_COLUMN_NAME}}
	]]></alterRenameColumn>

	<!-- 컬럼 수정 추가-->
	<alterModifyColumn><![CDATA[
		alter table {{TABLE_NAME}} modify {{COLUMN_NAME}} {{DATA_TYPE}} {{#equals true ddlOption.isNotNull}} not null {{/equals}} {{DEFAULT_VALUE}}
	]]></alterModifyColumn>

	<!-- 컬럼명 수정 추가-->
	<alterDropColumn><![CDATA[
		alter table {{TABLE_NAME}} drop  {{COLUMN_NAME}}
	]]></alterDropColumn>

	<!-- 테이블명 수정 추가-->
	<renameTable><![CDATA[
		rename table  {{TABLE_NAME}} as  {{NEW_TABLE_NAME}}
	]]></renameTable>
</var-ddl>

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddl_postgresql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE var-ddl SYSTEM  "ddlTemplate.dtd">

<var-ddl>
	<!-- 테이블 생성-->
	<tableScript><![CDATA[
COMMENT ON TABLE 테이블이름 IS '주석내용';
	]]></tableScript>

	<!-- view 생성-->
	<viewScript><![CDATA[
/* DROP VIEW {{objectName}}; */
CREATE view {{objectName}}
{{scriptSource}}
	]]></viewScript>

	<!-- function 생성-->
	<functionScript><![CDATA[
CREATE FUNCTION {{OBJECT_NAME}} ({{ARGUMENTS}}) RETURN {{RETURN_TYPE}}
AS LANGUAGE {{LANG}}
NAME {{SOURCE}};
	]]></functionScript>

	<!-- procedure 생성-->
	<procedureScript><![CDATA[
CREATE PROCEDURE {{OBJECT_NAME}} ({{ARGUMENTS}}) RETURN {{RETURN_TYPE}}
AS LANGUAGE {{LANG}}
NAME {{SOURCE}};
	]]></procedureScript>

	<!-- trigger 생성-->
	<triggerScript><![CDATA[
/* DROP TRIGGER ; */
CREATE OR REPLACE
	]]></triggerScript>

	<!-- index 생성-->
	<indexScript><![CDATA[

	]]></indexScript>

	<!-- sequence 생성-->
	<sequenceScript><![CDATA[
{{#equals true ddlOption.addDropClause}}/* DROP SEQUENCE {{OBJECT_NAME}}; */
{{/equals}}
CREATE SEQUENCE {{OBJECT_NAME}}
INCREMENT {{INCREMENT_BY}}
MINVALUE {{MIN_VALUE}}
MAXVALUE {{MAX_VALUE}}
START {{START_VALUE}}
{{#equals YES CYCLE_OPTION}}CYCLE
{{/equals}}
	]]></sequenceScript>

	<!-- 컬럼 추가-->
	<alterAddColumn><![CDATA[
alter table {{TABLE_NAME}} add ({{COLUMN_NAME}} {{DATA_TYPE}} {{DEFAULT_VALUE}})
	]]></alterAddColumn>

	<!-- 컬럼명 수정 추가-->
	<alterRenameColumn><![CDATA[
alter table {{TABLE_NAME}} rename column {{COLUMN_NAME}} to {{NEW_COLUMN_NAME}}
	]]></alterRenameColumn>

	<!-- 컬럼 수정 추가-->
	<alterModifyColumn><![CDATA[
alter table {{TABLE_NAME}} alter column {{COLUMN_NAME}} {{DATA_TYPE}} {{#equals true ddlOption.isNotNull}} not null {{/equals}} {{DEFAULT_VALUE}};
	]]></alterModifyColumn>

	<!-- 컬럼명 수정 추가-->
	<alterDropColumn><![CDATA[
alter table {{TABLE_NAME}} DROP {{COLUMN_NAME}}
	]]></alterDropColumn>

	<!-- 테이블명 수정 추가-->
	<renameTable><![CDATA[
alter table {{TABLE_NAME}} rename to {{NEW_TABLE_NAME}};
	]]></renameTable>
</var-ddl>

=== varsqlinfo/varsql/varsql-core/src/main/resources/db/template/ddl/ddl_other.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE var-ddl SYSTEM  "ddlTemplate.dtd">

<var-ddl>
	<!-- 테이블 생성-->
	<tableScript><![CDATA[
/* DROP TABLE {{objectName}} CASCADE CONSTRAINT; */
CREATE TABLE {{objectName}}(
	{{scriptSource}}
);

{{commnetSource}}
	]]></tableScript>

	<!-- view 생성-->
	<viewScript><![CDATA[
/* DROP VIEW {{objectName}}; */
CREATE view {{objectName}}
{{scriptSource}}
	]]></viewScript>

	<!-- function 생성-->
	<functionScript><![CDATA[
/* DROP FUNCTION {{objectName}}; */
CREATE OR REPLACE {{objectName}}
{{scriptSource}}
	]]></functionScript>

	<!-- procedure 생성-->
	<procedureScript><![CDATA[
/* DROP PROCEDURE {{objectName}}; */
CREATE OR REPLACE {{objectName}}
{{scriptSource}}
	]]></procedureScript>

	<!-- trigger 생성-->
	<triggerScript><![CDATA[
/* DROP TRIGGER {{objectName}}; */
CREATE OR REPLACE {{objectName}}
{{scriptSource}}
	]]></triggerScript>

	<!-- index 생성-->
	<indexScript><![CDATA[
/* DROP TRIGGER {{objectName}}; */
CREATE OR REPLACE {{objectName}}
{{scriptSource}}
	]]></indexScript>

	<!-- sequence 생성-->
	<sequenceScript><![CDATA[
CREATE SEQUENCE {{OBJECT_NAME}}
MINVALUE {{MIN_VALUE}}
MAXVALUE {{MAX_VALUE}}
INCREMENT BY {{INCREMENT_BY}} START WITH 0
CACHE {{CACHE}} NOORDER  NOCYCLE	]]></sequenceScript>

	<!-- 컬럼 추가-->
	<alterAddColumn><![CDATA[

	]]></alterAddColumn>

	<!-- 컬럼명 수정 추가-->
	<alterRenameColumn><![CDATA[

	]]></alterRenameColumn>

	<!-- 컬럼 수정 추가-->
	<alterModifyColumn><![CDATA[

	]]></alterModifyColumn>

	<!-- 컬럼명 수정 추가-->
	<alterDropColumn><![CDATA[

	]]></alterDropColumn>

	<!-- 테이블명 수정 추가-->
	<renameTable><![CDATA[
		alter table {{TABLE_NAME}} rename to {{NEW_TABLE_NAME}};
	]]></renameTable>
</var-ddl>
