=== varsqlinfo/varsql/varsql-core/src/main/resources/dtd/connection.config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dataSource (type,driver,url,username,password,max_active,pool_option,connection_option,timebetweenevictionrunsmillis,test_while_idle)>
<!ATTLIST dataSource name CDATA #REQUIRED>
<!ELEMENT type (#PCDATA)>
<!ELEMENT driver (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT max_active (#PCDATA)>
<!ELEMENT pool_option (#PCDATA)>
<!ELEMENT connection_option (#PCDATA)>
<!ELEMENT timebetweenevictionrunsmillis (#PCDATA)>
<!ELEMENT test_while_idle (#PCDATA)>

=== varsqlinfo/varsql/varsql-core/src/main/resources/config/varsqlConnectionConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataSource SYSTEM  "../dtd/connection.config.dtd">

<dataSource name="varsql">
	<type>local</type>
	<driver>org.h2.Driver</driver>
	<url>jdbc:h2:file:#resourePath#/varsql;AUTO_SERVER=TRUE;CACHE_SIZE=131072;</url>
	<username>sa</username>
	<password>sa</password>
	<max_active>10</max_active>
	<pool_option>max_idle=5;min_idle=5;</pool_option>
	<connection_option>sslConnection=true</connection_option>
	<timebetweenevictionrunsmillis>60000</timebetweenevictionrunsmillis>
	<test_while_idle>true</test_while_idle>
</dataSource>
